### ISSUE TITLE
support webpack v4 & vue-loader v15

### ISSUE THREAD

**Issue by kazupon** [kazupon/vue-i18n-loader#13]

**Comment by SeregPie** [comment]
Yes. Looks like it is not working on WebPack 4.
WebPack gives me this error.
```
ERROR in ./node_modules/@kazupon/vue-i18n-loader/lib!./path/to/file/i18n.json
Module parse failed: Unexpected token m in JSON at position 0
You may need an appropriate loader to handle this file type.
```

**Comment by Shyam-Chen** [comment]
https://github.com/numical/style-ext-html-webpack-plugin/pull/40

**Comment by mornir** [comment]
@exreplay 
I have a `vue.config.js` file with the following config:
```js
const merge = require('deepmerge')
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .tap(options =>
        merge(options, {
          loaders: {
            i18n: '@kazupon/vue-i18n-loader',
          },
        })
      )
  },
}
```
How can I edit it to use your workaround?

**Comment by exreplay** [comment]
@mornir 
It looks like you are using webpack-chain, which i had not much to do with but if im not mistaken, something like this should work:
```js
const merge = require('deepmerge')
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .tap(options =>
        merge(options, {
          loaders: {
            i18n: '@kazupon/vue-i18n-loader',
          },
        })
      )

    config.module
      .rule('json')
      .test(/\.js$/)
      .type('javascript/auto')
      .use('json')
      .loader('json-loader')
  },
}
```

**Comment by mornir** [comment]
@exreplay Thanks for your quick reply! 😃
I tried your code. First I got an error that said I should install `json-loader`, although it is supported by default by Wepback. I installed it nonetheless and then ran into a second error: 
```
Module build failed: SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.module.exports (C:\projects\speak\node_modules\json-loader\index.js:4:49)
```
Actually I am not in a hurry to use the latest vue-cli. I prefer to wait that @kazupon updates his how-to-use page: https://kazupon.github.io/vue-i18n/en/sfc.html#basic-usage

**Comment by exreplay** [comment]
@mornir You are welcome! :)
I am not that familiar with vue-cli and its configuration but i played around with it and got it to work. I did not think about that the newest version uses vue-loader 15 and therefore you need a different configuration.
```js
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('i18n')
      .resourceQuery(/blockType=i18n/)
      .type('javascript/auto')
      .use('i18n')
      .loader('@kazupon/vue-i18n-loader')
  }
}
```
It works with external files and embedded json. I used vue-cli v3.0.0-beta.10

**Comment by mornir** [comment]
@exreplay 
Works like a charm👍 Thanks 😉

**Comment by exreplay** [comment]
@mornir You are welcome, glad i could help you :)

**Comment by kazupon** [comment]
update readme.

**Comment by danielcommesse** [comment]
> @mornir You are welcome! :)
> I am not that familiar with vue-cli and its configuration but i played around with it and got it to work. I did not think about that the newest version uses vue-loader 15 and therefore you need a different configuration.
> 
> ```js
> module.exports = {
>   chainWebpack: config => {
>     config.module
>       .rule('i18n')
>       .resourceQuery(/blockType=i18n/)
>       .type('javascript/auto')
>       .use('i18n')
>       .loader('@kazupon/vue-i18n-loader')
>   }
> }
> ```
> 
> It works with external files and embedded json. You can also get rid of deepmerge and json-loader, as long as you dont need them in your project anywhere else. I used vue-cli v3.0.0-beta.10

Also worked for me with '@intlify/vue-i18n-loader'
