### ISSUE TITLE
How to use vue-i18n-loader with vue-loader 15?

### ISSUE THREAD

**Issue by smares** [kazupon/vue-i18n-loader#16]
With vue-loader 14, my Webpack 4 config has the following block:

```
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      i18n: '@kazupon/vue-i18n-loader'
    }
  }
},
```

After upgrading to the release candidate of vue-loader 15, none of my translations work, vue-i18n doesn't load any translation from `<i18n>` blocks within the `.vue` files.

Is this a known limitation or do I have to change anything in the Webpack 4 config? For vue-loader 15, I had to add `new VueLoaderPlugin(),` in the `plugins` section after adding `const { VueLoaderPlugin } = require('vue-loader')`

**Comment by Lanfei** [comment]
You can add following rule in your `webpack.conf.js`:

```js
{
  module: {
    rules: [
      {
        resourceQuery: /\bblockType=i18n\b/,
        loader: '@kazupon/vue-i18n-loader'
      }
      //, Other rules
    ]
  }
}
```

**Comment by smares** [comment]
Any idea how to then make it work with Webpack 4 which throws `Module parse failed: Unexpected token i in JSON at position 0`? With vue-loader 14, the hint from https://github.com/kazupon/vue-i18n-loader/issues/13 helped, but using your snippet from above no longers does the trick.

**Comment by Lanfei** [comment]
I am using Webpack 4.6.0 without `json-loader`, and it works fine for me.

**Comment by smares** [comment]
Are you using it with JSON files? As in `<i18n src="locale.en.json"/>`?

**Comment by smares** [comment]
Follow-up: It works if I rename the files to *.loca. Any idea how to make it work with *.json?

**Comment by smares** [comment]
```
{
  resourceQuery: /\bblockType=i18n\b/,
  loader: '@kazupon/vue-i18n-loader',
  type: 'javascript/auto'
}
```

This works. 👍

**Comment by Lanfei** [comment]
No, I was using `i18n` custom block like this, not with JSON files:

```html
<i18n>
{
  "en": {
    "hello": "hello world!"
  },
  "ja": {
    "hello": "こんにちは、世界！"
  }
}
</i18n>
```

**Comment by mekeor** [comment]
The documentation of vue-loader suggests to use `resourceQuery: /blockType=i18n/`. Why do you use `resourceQuery: /\bblockType=i18n\b/`? I.e. what does the `\b` do?

**Comment by mekeor** [comment]
I still couldn't get vue@2, vue-loader@15, vue-i18n, vue-i18n-loader and webpack@4 work together in single-file-components. I created a very minimal bare-bones repository here: https://github.com/mekeor/webpack4-vue2-vueLoader15-vueI18n-vueI18nLoader-singleFileComponent

I'm gettings this error:
![2018-05-02-005258_1138x141_scrot](https://user-images.githubusercontent.com/812632/39497393-75d9b9d0-4da3-11e8-9172-99f9ea05c7cb.png)

@Lanfei Would you mind telling me what I'm doing wrong? You seem to have working exactly what I'm trying to achieve.

**Comment by Edza** [comment]
The workaround has a heavy performance impact on compilation. I also can not exclude node_modules folder (vue-loader complains it can not find it's own folder for some reason).

Please make fixing this a priority, I'll see if I can contribute. Can't we use the generic i18n-loader and take the working parts and insert into vue?

**Comment by Lanfei** [comment]
@mekeor Sorry that I was on a trip in the past week, have you solved your problem?

**Comment by mekeor** [comment]
Yes, I solved my problem (– by moving away from vue-i18n, sorry –) but thank you :)

**Comment by Edza** [comment]
@mekeor Where did you move? Just using the regular webpack i18n loader? I'm using the workaround and it works fine more or less.

**Comment by mekeor** [comment]
My project is tiny, so I just wrote my own few lines of code for that little internationalization I need. :woman_shrugging:

**Comment by Edza** [comment]
Ah well, I work with many other programmers on the vue components, so we really need this thing to work. But yeah, the workarond is ok, the performance impact is not bad if you set json-loader to use only your .json files in your specific i18n .json file folder.
