### ISSUE TITLE
Parcel Support

### ISSUE THREAD

**Issue by evanleck** [kazupon/vue-i18n-loader#19]
I'm not sure if this is the right place to ask, but I'm interested in using `<i18n>` custom blocks in SFCs built with [Parcel](https://parceljs.org). I'm not terribly familiar with how that might work but I was wondering if that was on your radar yet or you might be able to add support?

Thanks!

**Comment by evanleck** [comment]
Never mind, it looks like [there's a PR open already](https://github.com/parcel-bundler/parcel/pull/1775) to add support directly to Parcel. Sorry!

**Comment by 0x1af2aec8f957** [comment]
Has the problem finally been solved? Recently, I was using parcel to build a new project and got stuck in this place.

Although the official website of parcel introduces the custom Vue single file block parsing, I can't find a suitable vue-i18n plug-in to handle the parsing. Does vue-i18n not provide an out of the box solution for parcel?

```json
//  .vuerc
/// doc: https://parceljs.org/languages/vue/#custom-blocks
{
  "customBlocks": {
    // "i18n": "vue-i18n-bridge/dist/vue-i18n-bridge.runtime.esm-bundler.js"
    // "i18n": "@intlify/vite-plugin-vue-i18n"
    // "i18n": "@intlify/unplugin-vue-i18n"
  }
}
```
