### ISSUE TITLE
Multiple translations format

### ISSUE THREAD

**Issue by treatys** [kazupon/vue-i18n-loader#25]
It would be nice to support YAML and JSON format side by side. It can be achieved for example by adding attribute lang="yaml". 

Also, with vue-loader v15 I cannot make YAML working inside i18n block by any means. Supporting YAML natively would solve my problem.

**Comment by chiaweilee** [comment]
`YAML to JSON loader` before `vue-i18n-loader`?

**Comment by kazupon** [comment]
Supported with this commit.
https://github.com/kazupon/vue-i18n-loader/commit/36c62a5bf97182ec0ae9dc84404a033f0042f474

close
