### ISSUE TITLE
Lazy loading compatibility

### ISSUE THREAD

**Issue by soniktrooth** [kazupon/vue-i18n-loader#33]
Does the use of `<i18n>` blocks inside of components defeat the point of lazy loading? Or does webpack handle this some how even though the strings aren't stored in separate files before build?

**Comment by kazupon** [comment]
The locale messages of `<i18n>` blocks is included Vue Components. 
Lazy loading works.

**Comment by williamweckl** [comment]
@kazupon I have some doubts about it. Is the component lazy loaded at all with all i18n strings or just the user selected locale messages?

I really like the approach of this library, but if I have for example 3 locales with 10 translated messages it, all the 30 translated messages will be loaded inside the js file? Or somehow can we handle and load this translation messages separated to only load those 10 that is from the user's selected locale?

**Comment by ducmerida** [comment]
@kazupon 
I'm also interested on this functionality, I want to lazy load the json files declared on `<i18n>` block (separated chunks for every block).

**Comment by Velikolay** [comment]
Curious about that too. It seems like the lazy loading works with a single file per locale? In a lot of the cases a single page needs just a fraction of the strings and loading all of them can be an overkill?

**Comment by pperzyna** [comment]
@kazupon This does not work well.

**Comment by kazupon** [comment]
<i18n> custom block will be bundled with SFC.
That means that lazy loading is possible using Vue asynchronous component mechanism.

https://v3.vuejs.org/guide/migration/async-components.html#async-components

**Comment by Grawl** [comment]
@kazupon it means all locales of components will be loaded with component chunk. we want to load only one locale. Imagine I have 7 locales for each component but want to download only 1 active locale.
