### ISSUE TITLE
SFC i18n block breaks debug

### ISSUE THREAD

**Issue by oorooroot** [kazupon/vue-i18n-loader#34]
I'm currently using VSCode for vue frontend development, and when i add single <i18n> block, to any component, IDE debug totally brokes for entire project. I cant find what causes wrong behavior, but  i am pretty sure, that it happens when i add this <i18n> block.

**Comment by kazupon** [comment]
This is not issue of vue-i18n-loader.
maybe, I think that it' is issue of vscode. if you use vetur, I think it's is issue of vetur.
Thanks!
