### ISSUE TITLE
Using vue-i18n-loader with karma

### ISSUE THREAD

**Issue by Korri** [kazupon/vue-i18n-loader#4]
I have set my `.vue` loader properly, and it works properly on chrome, but when I run my karma unit test suite (which uses the same web-pack config with a few changes), I get the following message for all my translations:
```
[vue-i18n] Cannot translate the value of keypath 'example_key'. Use the value of keypath as default.
```

Is there something that needs to be done in order to have this plugin work with `karma-webpack`?

**Comment by kazupon** [comment]
Thank you for your reporting!

Can you provide minimum reproduction repo please?

**Comment by Korri** [comment]
Here I created an basic project using `vue init webpack` and reproduced the issue.

Repository is here: https://github.com/Korri/vue-i18n-issue-demo

It works on the dev server `npm run dev`
but fails in the unit test `npm run unit`

**Comment by kazupon** [comment]
Thank you for your repo!

This issues is bug of vue-i18n.
For this reason, closed.
