### ISSUE TITLE
Usage with pug

### ISSUE THREAD

**Issue by kyrsquir** [kazupon/vue-i18n-loader#54]
Hey and thanks for an awesome plugin!

Is it possible to write pug code inside `<i18n lang="yaml">` blocks? I have some Nuxt pages consisting of localised text mixed with markup, the latter being different between locales. Currently all my templates are written in pug and I'd like to leave it this way. How do I configure the plugin and webpack to convert pug code within yaml blocks to html before passing it to v-html?

Or perhaps I'm doing it the wrong way and I should look towards creating a separate Nuxt page for each locale?

**Comment by kazupon** [comment]
Thank you for your feedback!

As use-case of i18n custom block, It provides the Vue component with resource management of locale messages.
If you want to write a pug, you need to write it on the `template`.

Thanks!
