### ISSUE TITLE
npm command not working

### ISSUE THREAD

**Issue by fredarchimed** [kazupon/vue-i18n-loader#9]
Hello,

I tried to install vue-i18n-loader this morning with the standard command:
``npm i --save @kazupon/vue-i18n-loader``

I have the following error:
```npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@kazupon/vue-i18n-loader" "--save"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @kazupon/vue-i18n-loader
npm ERR! 404
npm ERR! 404  '@kazupon/vue-i18n-loader' is not in the npm registry.
```

I also tried to add it manually in the package.json with the same effect:
``"@kazupon/vue-i18n-loader": "^0.2.1"``

I found a strange workaround removing the @ in the command line:
``npm i --save kazupon/vue-i18n-loader``  
=> it adds the following ugly line in the dependencies:
``"@kazupon/vue-i18n-loader": "github:kazupon/vue-i18n-loader"``

It works but it's not clean.

**Comment by kazupon** [comment]
close due to cannot reproduce
